export default [
  {
    name: "Project Initialized",
    description: "Laying the foundation for the Canxium Blockchain. First commit!",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 0,
  },
  {
    name: "Genesis Initialized",
    description: "Laying the foundation of the genesis block.",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 1,
  },
  {
    name: "Difficulty Base Reward Implementation",
    description: "Reward PoW miners based on the difficulty of the block.",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 2,
  },
  {
    name: "Blockchain Launch",
    description: "The Canxium Blockchain was launched on Apr 30 2023 20:06:16 PM (+07:00 UTC).",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 3,
  },
  {
    name: "Canxium Litepaper",
    description: "Working on the litepaper to draft the canxium vision and ideas.",
    status: "Completed",
    year: "2023",
    tag: "Research",
    priority: "High",
    quarter: "Q2",
    index: 4,
  },
  {
    name: "Network Stats",
    description: "A visual interface for tracking canxium status.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "Medium",
    quarter: "Q2",
    index: 5,
  },
  {
    name: "Coin Supply",
    description: "A visual interface & API for tracking canxium supply.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "Medium",
    quarter: "Q3",
    index: 6,
  },
  {
    name: "Canxium Whitepaper v0.0.1",
    description: "General overview of the project, featuring technical explanations.",
    status: "Completed",
    year: "2023",
    tag: "Research",
    priority: "High",
    quarter: "Q3",
    index: 7,
  },
  {
    name: "Block Explorer",
    description: "Interface to track and verify txs on the network.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q3",
    index: 8,
  },
  {
    name: "Canxium Faucet",
    description: "Easily receive dust in your wallet to interact with the Canxium testnet.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 9,
  },
  {
    name: "Canxium Swap",
    description: "Swap your canxium tokens with other tokens on the network.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 10,
  },
  {
    name: "Swap Analytics",
    description: "Analyze the swap data from the network.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 11,
  },
  {
    name: "Bridge Contract Audit",
    description: "Audit the bridge contract for security vulnerabilities.",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q4",
    index: 12,
  },
  {
    name: "Canxium Bridge",
    description: "Bridge assets between Canxium and other networks.",
    status: "Completed",
    year: "2023",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q4",
    index: 13,
  },
  {
    name: "Revamp Canxium Swap & Bridge UI/UX",
    description: "Revamp the Canxium Swap & Bridge UI/UX.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 14,
  },
  {
    name: "Host Zealy Campaign",
    description: "Host a campaign on Zealy to promote the Canxium project.",
    status: "Completed",
    year: "2023",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q4",
    index: 15,
  },
  {
    name: "Canxium Improvement Proposals (CIPs)",
    description: "Standardize and provide high-quality documentation for Canxium itself and conventions built upon it.",
    status: "Completed",
    year: "2023",
    tag: "Research",
    priority: "High",
    quarter: "Q4",
    index: 16,
  },
  {
    name: "Canxium Listing Campaign",
    description: "Listing campaign for Canxium on multiple exchanges.",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 17,
  },
  {
    name: "Gleam Campaign",
    description: "Host a campaign on Gleam to promote the Canxium project with Dojima.",
    status: "Completed",
    year: "2023",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q4",
    index: 18,
  },
  {
    name: "AMA",
    description: "Host an AMA to answer questions from the community with Dojima.",
    status: "Completed",
    year: "2023",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q4",
    index: 19,
  },
  {
    name: "Minerstat",
    description: "List Canxium on Minerstat to help users find the best mining pools & tools",
    status: "Completed",
    year: "2023",
    tag: "App",
    priority: "Medium",
    quarter: "Q4",
    index: 20,
  },
  {
    name: "Add to CoinMarketCap",
    description: "Add Canxium to CoinMarketCap",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "Medium",
    quarter: "Q1",
    index: 21,
  },
  {
    name: "Canxium Wallet",
    description: "The official Canxium wallet, written in Flutter.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q1",
    index: 22,
  },
  {
    name: "Research PoS",
    description: "Research and study the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "Research",
    priority: "High",
    quarter: "Q1",
    index: 23,
  },
  {
    name: "PoS Testnet",
    description: "Create a testnet for the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 24,
  },
  {
    name: "AMA with Crypto_Kaiba",
    description: "AMA with Crypto_Kaiba to answer questions from the community.",
    status: "Completed",
    year: "2024",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q1",
    index: 25,
  },
  {
    name: "PoS Launchpads",
    description: "Create a launchpads for the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 26,
  },
  {
    name: "Genesis Update v0.0.2",
    description: "Update the genesis block to include the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q1",
    index: 27,
  },
  {
    name: "Update Whitepaper",
    description: "Update the whitepaper to introduce new mining rewards for the Ethash algorithm.",
    status: "Completed",
    year: "2024",
    tag: "Research",
    priority: "High",
    quarter: "Q1",
    index: 28,
  },
  {
    name: "PoS Tools",
    description: "Create a tools for the PoS consensus mechanism: Validator keys generation, validator registration, etc.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q1",
    index: 29,
  },
  {
    name: "Start PoS Sidechain",
    description: "Start the PoS sidechain for the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 30,
  },
  {
    name: "PoS Explorer",
    description: "A visual interface for tracking canxium PoS slots, epochs, and more.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q2",
    index: 31,
  },  {
    name: "Bridge Maintenance",
    description: "Maintain the bridge",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "Meidum",
    quarter: "Q2",
    index: 32,
  },
  {
    name: "Audit Canxium",
    description: "Audit the Canxium blockchain for security vulnerabilities, by CertiK.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 33,
  },
  {
    name: "Genesis Update v0.0.3",
    description: "Update the genesis to include the Offline Mining Protocol.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 34,
  },
  {
    name: "Network Upgrade #1",
    description: "Deploy the offline mining at block 4204800 and remove the fixed mining reward of 0.25 CAU",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 35,
  },
  {
    name: "Hydro Hardfork",
    description: "Support for Ethash mining protocol, for the Canxium blockchain, through new mining protocol, parallel to PoS.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 36,
  },
  {
    name: "Merge to PoS",
    description: "Merge the Canxium blockchain to the PoS consensus mechanism.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q3",
    index: 37,
  },
  {
    name: "Introduce Dino Game",
    description: "Introduce the Dino Game to the Canxium blockchain via a Telegram bot.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "Low",
    quarter: "Q3",
    index: 38,
  },
  {
    name: "Cappella Hardfork",
    description: "Allow validtors to withdraw their stake.",
    status: "Completed",
    year: "2024",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q3",
    index: 39,
  },
  {
    name: "Community Sharing Program",
    description: "Introduce a community sharing program to reward the community for their contributions.",
    status: "Completed",
    year: "2024",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q3",
    index: 40,
  },
  {
    name: "Dex Update",
    description: "Update the Dex to support WalletConnect.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "Medium",
    quarter: "Q3",
    index: 41,
  },
  {
    name: "Documentations",
    description: "Comprehensive project resources: detailed guides, feature overviews, APIs, and more.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 42,
  },
  {
    name: "Canxium x Wow3",
    description: "Partnership with Wow3 to promote the Canxium project.",
    status: "Completed",
    year: "2024",
    tag: "Awareness",
    priority: "Medium",
    quarter: "Q4",
    index: 43,
  },
  {
    name: "Canxium x Geckoterminal",
    description: "Partnership with Geckoterminal to track the Canxium blockchain metadata.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "Medium",
    quarter: "Q4",
    index: 44,
  },
  {
    name: "Update Whitepaper",
    description: "Revamp the whitepaper and move to the Canxium website.",
    status: "Completed",
    year: "2024",
    tag: "Research",
    priority: "High",
    quarter: "Q4",
    index: 45,
  },
  {
    name: "Canxium x Tangem",
    description: "Partnership with Tangem to create a secure and easy-to-use wallet for the Canxium blockchain.",
    status: "Completed",
    year: "2024",
    tag: "App",
    priority: "High",
    quarter: "Q4",
    index: 46,
  },
  {
    name: "Research Cross-Chain Mining",
    description: "Research the possibility of cross-chain mining for the Canxium blockchain.",
    status: "Completed",
    year: "2024",
    tag: "Research",
    priority: "High",
    quarter: "Q4",
    index: 47,
  },
  {
    name: "Canxium x Kaspa Cross-Chain Mining",
    description: "Implement the cross-chain mining protocol for the Canxium blockchain with Kaspa.",
    status: "Completed",
    year: "2025",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 48,
  },
  {
    name: "Genesis Update v0.0.4",
    description: "Update the genesis to include the cross-chain mining protocol with Kaspa.",
    status: "Completed",
    year: "2025",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 49,
  },
  {
    name: "Canxium Retained Proof of Work",
    description: "Introduce the retained proof of work protocol for the Canxium blockchain.",
    status: "Completed",
    year: "2025",
    tag: "Research",
    priority: "High",
    quarter: "Q1",
    index: 50,
  },
  {
    name: "Helium Hardfork",
    description: "Enabling Cross-Chain Mining With Kaspa.",
    status: "Completed",
    year: "2025",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q1",
    index: 51,
  },
  {
    name: "Canxium x WhalePool, K1Pool, Humpool, etc.",
    description: "Partnership with WhalePool, K1Pool, Humpool, EMCD, etc. to support cross-chain mining.",
    status: "Completed",
    year: "2025",
    tag: "App",
    priority: "Medium",
    quarter: "Q1",
    index: 52,
  },
  {
    name: "Cross-Chain Mining Criteria",
    description: "Cross-Chain Mining Criteria for Mining Pool",
    status: "Completed",
    year: "2025",
    tag: "Research",
    priority: "Medium",
    quarter: "Q1",
    index: 53,
  },
  {
    name: "Cross-Chain Mining: Monero",
    description: "Research the possibility of cross-chain mining with Monero.",
    status: "Cancelled",
    year: "2025",
    tag: "Research",
    priority: "Medium",
    quarter: "Q1",
    index: 54,
  },
  {
    name: "Market Making",
    description: "Build MM Tools for the Canxium project.",
    status: "In Progress",
    year: "2025",
    tag: "App",
    priority: "High",
    quarter: "Q2",
    index: 55,
  },
  {
    name: "Cross-Chain Mining: Ravencoin",
    description: "Research the possibility of cross-chain mining with Ravencoin.",
    status: "In Progress",
    year: "2025",
    tag: "Research",
    priority: "High",
    quarter: "Q2",
    index: 56,
  },
  {
    name: "Cross-Chain Mining: Ravencoin",
    description: "Update the cross-chain mining protocol to support Ravencoin.",
    status: "Planned",
    year: "2025",
    tag: "Blockchain",
    priority: "High",
    quarter: "Q2",
    index: 57,
  },
  {
    name: "Live AMA with Co-Founder: The Future of PoW Mining",
    description: "Join our first-ever live AMA with the co-founder as we dive into the vision, roadmap, and groundbreaking developments ahead - including offline mining, zk-proofs, and cross-mining integration.",
    status: "Completed",
    year: "2025",
    tag: "Awareness",
    priority: "High",
    quarter: "May 18",
    index: 58,
  },
  {
    name: "Cross-Chain Mining: Zcash",
    description: "Research the possibility of cross-chain mining with Zcash.",
    status: "Planned",
    year: "2025",
    tag: "Research",
    priority: "Medium",
    quarter: "Q3",
    index: 59,
  },
  {
    name: "Cross-Chain Mining: Dash",
    description: "Research the possibility of cross-chain mining with Dash.",
    status: "Planned",
    year: "2025",
    tag: "Research",
    priority: "Medium",
    quarter: "Q3",
    index: 60,
  },
  {
    name: "Update The Bridge",
    description: "Bridge Improvements and Upgrade Research",
    status: "Planned",
    year: "2025",
    tag: "Research",
    priority: "Medium",
    quarter: "Q3",
    index: 61,
  },
  {
    name: "Cross-Chain Mining: Kaspa",
    description: "Reduce the load on the Canxium when verifying Kaspa PoW.",
    status: "Planned",
    year: "2025",
    tag: "Research",
    priority: "High",
    quarter: "Q3",
    index: 62,
  },
  {
    name: "Research RETH",
    description: "Research to use RETH client besides GETH to increase network reliability.",
    status: "Planned",
    year: "2025",
    tag: "Research",
    priority: "High",
    quarter: "Q4",
    index: 63,
  }
]
